export const INDIA_CONFIG = {
  // GST Configuration
  GST: {
    API_BASE_URL: process.env.GST_API_URL || 'https://api.gst.gov.in',
    GSTIN_REGEX: /^[0-9]{2}[A-Z]{5}[0-9]{4}[A-Z]{1}[1-9A-Z]{1}Z[0-9A-Z]{1}$/,
    STATES: {
      '01': 'Jammu and Kashmir',
      '02': 'Himachal Pradesh',
      '03': 'Punjab',
      '04': 'Chandigarh',
      '05': 'Uttarakhand',
      '06': 'Haryana',
      '07': 'Delhi',
      '08': 'Rajasthan',
      '09': 'Uttar Pradesh',
      '10': 'Bihar',
      '11': 'Sikkim',
      '12': 'Arunachal Pradesh',
      '13': 'Nagaland',
      '14': 'Manipur',
      '15': 'Mizoram',
      '16': 'Tripura',
      '17': 'Meghalaya',
      '18': 'Assam',
      '19': 'West Bengal',
      '20': 'Jharkhand',
      '21': 'Odisha',
      '22': 'Chhattisgarh',
      '23': 'Madhya Pradesh',
      '24': 'Gujarat',
      '25': 'Daman and Diu',
      '26': 'Dadra and Nagar Haveli',
      '27': 'Maharashtra',
      '29': 'Karnataka',
      '30': 'Goa',
      '31': 'Lakshadweep',
      '32': 'Kerala',
      '33': 'Tamil Nadu',
      '34': 'Puducherry',
      '35': 'Andaman and Nicobar Islands',
      '36': 'Telangana',
      '37': 'Andhra Pradesh',
    },
  },

  // MSME Configuration
  MSME: {
    UDYAM_API_URL: process.env.UDYAM_API_URL || 'https://udyamregistration.gov.in/api',
    CATEGORIES: {
      MICRO: { investment: 1000000, turnover: 5000000 }, // ₹1 Cr, ₹5 Cr
      SMALL: { investment: 10000000, turnover: 50000000 }, // ₹10 Cr, ₹50 Cr
      MEDIUM: { investment: 50000000, turnover: 250000000 }, // ₹50 Cr, ₹250 Cr
    },
  },

  // Regional Languages
  LANGUAGES: {
    eng: {name: 'English', code: 'eng', rtl: false },
    hi: { name: 'हिंदी', code: 'hi', rtl: false },
    ta: { name: 'தமிழ்', code: 'ta', rtl: false },
    te: { name: 'తెలుగు', code: 'te', rtl: false },
    gu: { name: 'ગુજરાતી', code: 'gu', rtl: false },
    kn: { name: 'ಕನ್ನಡ', code: 'kn', rtl: false },
    ml: { name: 'മലയാളം', code: 'ml', rtl: false },
    mr: { name: 'मराठी', code: 'mr', rtl: false },
    bn: { name: 'বাংলা', code: 'bn', rtl: false },
    pa: { name: 'ਪੰਜਾਬੀ', code: 'pa', rtl: false },
    or: { name: 'ଓଡ଼ିଆ', code: 'or', rtl: false },
  },

  // Industry Presets for India
  INDUSTRY_PRESETS: {
    TEXTILES: {
      name: 'Textiles & Garments',
      certifications: ['GOTS', 'Handloom Mark', 'ZED', 'BIS'],
      documents: ['Handloom Certificate', 'GOTS Certificate', 'Factory License'],
      compliance: ['GST', 'MSME', 'Labour License'],
    },
    AGRICULTURE: {
      name: 'Agriculture & Food',
      certifications: ['APEDA', 'FSSAI', 'Organic India'],
      documents: ['FSSAI License', 'Organic Certificate', 'APEDA Registration'],
      compliance: ['GST', 'FSSAI', 'APEDA'],
    },
    PHARMA: {
      name: 'Pharmaceuticals',
      certifications: ['CDSCO', 'WHO-GMP', 'ISO 13485'],
      documents: ['Drug License', 'Manufacturing License', 'GMP Certificate'],
      compliance: ['GST', 'CDSCO', 'Drug Controller'],
    },
    AUTO: {
      name: 'Automotive Components',
      certifications: ['AIS', 'TS 16949', 'ARAI'],
      documents: ['Type Approval', 'AIS Certificate', 'ARAI Test Report'],
      compliance: ['GST', 'AIS', 'Automotive Standards'],
    },
    LEATHER:{
      name: 'Leather Goods',
      certifications: ['Leather Working Group', 'ISO 14001'],
      documents: ['LWG Certificate', 'Environmental Clearance'],
      compliance: ['GST', 'MSME', 'Environmental Compliance'],
    },
    ENGINEERING_GOODS: {
      name: 'Engineering Goods',
      certifications: ['ISO 9001', 'CE Marking'],
      documents: ['Quality Certificate', 'CE Compliance'],
      compliance: ['GST', 'MSME', 'Quality Standards'],
    },
    MANUFACTURING: {
      name: 'General Manufacturing',
      certifications: ['ISO 9001', 'ISO 14001'],
      documents: ['Quality Certificate', 'Environmental Clearance'],
      compliance: ['GST', 'MSME', 'Labour License'],
    },
    ELECTRONICS: {
      name: 'Electronics & IT',
      certifications: ['ISO 9001', 'RoHS', 'CE Marking'],
      documents: ['Quality Certificate', 'RoHS Compliance'],
      compliance: ['GST', 'MSME', 'IT Act Compliance'],
    },
    WOOD_PRODUCTS: {
      name: 'Wood & Furniture',
      certifications: ['FSC', 'ISO 14001'],
      documents: ['FSC Certificate', 'Environmental Clearance'],
      compliance: ['GST', 'MSME', 'Environmental Compliance'],
    },
    PAPER_PRINTING: {
      name: 'Paper & Printing',
      certifications: ['FSC', 'ISO 9001'],
      documents: ['FSC Certificate', 'Quality Certificate'],
      compliance: ['GST', 'MSME', 'Environmental Compliance'],
    },
    GEMS_JEWELLERY: {
      name: 'Gems & Jewellery',
      certifications: ['GIA', 'IGI', 'BIS'],
      documents: ['Hallmark Certificate', 'GIA Report'],
      compliance: ['GST', 'MSME', 'BIS Compliance'],
    },
    HANDICRAFTS: {
      name: 'Handicrafts',
      certifications: ['Geographical Indication', 'Handloom Mark'],
      documents: ['GI Certificate', 'Handloom Certificate'],
      compliance: ['GST', 'MSME', 'Cultural Heritage Compliance'],
    },
    RENEWABLE_ENERGY: {
      name: 'Renewable Energy',
      certifications: ['ISO 50001', 'IEC Standards'],
      documents: ['Energy Audit Report', 'Compliance Certificate'],
      compliance: ['GST', 'MSME', 'Environmental Compliance'],
    },
    NON_METALLIC_MINERALS: {
      name: 'Non-Metallic Minerals',
      certifications: ['ISO 9001', 'Environmental Clearance'],
      documents: ['Mining License', 'Quality Certificate'],
      compliance: ['GST', 'MSME', 'Environmental Compliance'],
    },
    RUBBER_PLASTICS: {
      name: 'Rubber & Plastics',
      certifications: ['ISO 9001', 'RoHS'],
      documents: ['Quality Certificate', 'RoHS Compliance'],
      compliance: ['GST', 'MSME', 'Environmental Compliance'],
    },

  },

  // Pricing in INR (India-focused)
  PRICING_TIERS: {
    JAN_SE: {
      id: 'jan_se',
      name: 'Jan Se',
      price: 0,
      currency: 'INR',
      interval: 'month',
      features: {
        products: 1,
        suppliers: 5,
        gstValidation: true,
        msmeVerification: false,
        regionalLanguage: true,
        basicReports: true,
        whatsappSupport: false,
        apiAccess: false,
      },
      target: 'Micro-enterprises',
    },
    UDYAM: {
      id: 'udyam',
      name: 'Udyam',
      price: 1499,
      currency: 'INR',
      interval: 'month',
      features: {
        products: 10,
        suppliers: 50,
        gstValidation: true,
        msmeVerification: true,
        regionalLanguage: true,
        basicReports: true,
        whatsappSupport: true,
        apiAccess: true,
        gstAutoFiling: true,
        ewayBillIntegration: true,
      },
      target: 'Small factories',
      popular: true,
    },
    UNNATI: {
      id: 'unnati',
      name: 'Unnati',
      price: 4999,
      currency: 'INR',
      interval: 'month',
      features: {
        products: 'unlimited',
        suppliers: 'unlimited',
        gstValidation: true,
        msmeVerification: true,
        regionalLanguage: true,
        basicReports: true,
        whatsappSupport: true,
        apiAccess: true,
        gstAutoFiling: true,
        ewayBillIntegration: true,
        bisCompliance: true,
        apedaCompliance: true,
        customReports: true,
        dedicatedSupport: true,
      },
      target: 'Exporters',
    },
  },

  // Payment Methods (India-specific)
  PAYMENT_METHODS: {
    UPI: ['UPI AutoPay', 'UPI QR', 'UPI Collect'],
    BANKING: ['NEFT', 'RTGS', 'IMPS'],
    CARDS: ['Debit Card', 'Credit Card'],
    WALLETS: ['Paytm', 'PhonePe', 'Google Pay'],
    EMI: ['Razorpay EMI', 'Bank EMI'],
  },

  // Document Types (India-specific)
  DOCUMENT_TYPES: {
    UDYAM: 'Udyam Registration Certificate',
    GSTIN: 'GST Registration Certificate',
    FSSAI: 'FSSAI License',
    BIS: 'BIS Certification',
    EWAY_BILL: 'E-way Bill',
    HANDLOOM: 'Handloom Mark Certificate',
    GOTS: 'Global Organic Textile Standard',
    APEDA: 'APEDA Registration',
    CDSCO: 'CDSCO License',
    AIS: 'AIS Certification',
    ISO: 'ISO Certification',
    ARAI: 'ARAI Test Report',
    QUALITY: 'Quality Compliance Certificate',
    ENVIRONMENTAL: 'Environmental Clearance Certificate',
    HALLMARK: 'Hallmark Certificate',
    GI: 'Geographical Indication Certificate',

  },

  // Pilot States
  PILOT_STATES: {
    TAMIL_NADU: {
      code: 'TN',
      name: 'Tamil Nadu',
      industry: 'Textiles',
      language: 'ta',
      focus: 'Handloom mark verification',
    },
    KERALA: {
      code: 'KL',
      name: 'Kerala',
      industry: 'Spices',
      language: 'ml',
      focus: 'FSSAI traceability',
    },
    HARYANA: {
      code: 'HR',
      name: 'Haryana',
      industry: 'Auto Components',
      language: 'hi',
      focus: 'AIS certification',
    },
    TELANGANA: {
      code: 'TS',
      name: 'Telangana',
      industry: 'Pharma',
      language: 'te',
      focus: 'CDSCO compliance',
    },
    MAHARASHTRA: {
      code: 'MH',
      name: 'Maharashtra',
      industry: 'Engineering Goods',
      language: 'mr',
      focus: 'ISO certification',
    },
    GUJARAT: {
    code: 'GJ',
    name: 'Gujarat',
    industry: 'Gems & Jewellery',
    language: 'gu',
    focus: 'BIS & Hallmark verification',
    documents: ['Hallmark Certificate', 'BIS Certification', 'GIA Report'],
  },
  WEST_BENGAL: {
    code: 'WB',
    name: 'West Bengal',
    industry: 'Handicrafts',
    language: 'bn',
    focus: 'Geographical Indication & Handloom Mark',
    documents: ['GI Certificate', 'Handloom Certificate'],
  },
  KARNATAKA: {
    code: 'KA',
    name: 'Karnataka',
    industry: 'Electronics & IT',
    language: 'kn',
    focus: 'RoHS and IT Act compliance',
    documents: ['RoHS Compliance', 'Quality Certificate', 'IT Act Compliance'],
  },
  PUNJAB: {
    code: 'PB',
    name: 'Punjab',
    industry: 'Food Processing',
    language: 'pa',
    focus: 'FSSAI & APEDA certification',
    documents: ['FSSAI License', 'APEDA Registration', 'Organic Certificate'],
  },
  RAJASTHAN: {
    code: 'RJ',
    name: 'Rajasthan',
    industry: 'Leather Goods',
    language: 'hi',
    focus: 'LWG & Environmental compliance',
    documents: ['LWG Certificate', 'Environmental Clearance'],
  },
  UTTAR_PRADESH: {
    code: 'UP',
    name: 'Uttar Pradesh',
    industry: 'Paper & Printing',
    language: 'hi',
    focus: 'FSC mark certification',
    documents: ['FSC Certificate', 'Quality Certificate'],
  },
  MADHYA_PRADESH: {
    code: 'MP',
    name: 'Madhya Pradesh',
    industry: 'Agriculture',
    language: 'hi',
    focus: 'FSSAI & APEDA traceability',
    documents: ['Organic Certificate', 'FSSAI License'],
  },
  ODISHA: {
    code: 'OD',
    name: 'Odisha',
    industry: 'Non-Metallic Minerals',
    language: 'or',
    focus: 'Mining & environmental clearance',
    documents: ['Mining License', 'Environmental Clearance'],
  },
  ANDHRA_PRADESH: {
    code: 'AP',
    name: 'Andhra Pradesh',
    industry: 'Renewable Energy',
    language: 'te',
    focus: 'ISO 50001 & IEC Standards',
    documents: ['Energy Audit Report', 'Compliance Certificate'],
  },
  CHHATTISGARH: {
    code: 'CG',
    name: 'Chhattisgarh',
    industry: 'Rubber & Plastics',
    language: 'hi',
    focus: 'RoHS & ISO compliance',
    documents: ['RoHS Compliance Certificate', 'Quality Certificate'],
  },
  

  },
};

export const COMPLIANCE_REQUIREMENTS = {
  GST: {
    mandatory: true,
    documents: ['GST Registration Certificate', 'GSTR-1', 'GSTR-3B'],
    validationAPI: 'https://api.gst.gov.in/taxpayerapi/search',
  },
  MSME: {
    optional: true,
    benefits: ['Credit Guarantee', 'Delayed Payment Protection', 'Government Procurement Preference'],
    documents: ['Udyam Registration Certificate'],
  },
  FSSAI: {
    industries: ['AGRICULTURE'],
    mandatory: true,
    documents: ['FSSAI License', 'Food Safety Certificate'],
  },
  BIS: {
    industries: ['TEXTILES', 'AUTO'],
    documents: ['BIS Certification', 'ISI Mark'],
  },
  APEDA: {
    industries: ['AGRICULTURE'],
    documents: ['APEDA Registration', 'Organic Certification'],
  },
  AIS: {
    industries: ['AUTO'],
    documents: ['AIS Certification', 'Type Approval Certificate'],
  },
  CDSCO: {
    industries: ['PHARMA'],
    documents: ['CDSCO License', 'Drug Manufacturing License'],
  },
  ENVIRONMENTAL: {
    industries: ['MANUFACTURING', 'ENGINEERING_GOODS', 'RUBBER_PLASTICS'],
    documents: ['Environmental Clearance Certificate', 'Pollution Control Board License'],
  },
  QUALITY: {
    industries: ['MANUFACTURING', 'ENGINEERING_GOODS', 'ELECTRONICS'],
    documents: ['ISO Certification', 'Quality Compliance Certificate'],
  },
  HALLMARK: {
    industries: ['GEMS_JEWELLERY'],
    documents: ['Hallmark Certificate', 'Assaying Report'],
  },
  GI: {
    industries: ['HANDICRAFTS'],
    documents: ['Geographical Indication Certificate', 'Cultural Heritage Compliance'],
  },
  ROHS: {
    industries: ['ELECTRONICS', 'RUBBER_PLASTICS'],
    documents: ['RoHS Compliance Certificate', 'Environmental Compliance'],
  },
  LWG: {
    industries: ['LEATHER'],
    documents: ['Leather Working Group Certification', 'Environmental Compliance'],
  },
  
};